# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/random-headers',
                'doc_host': 'https://INF800.github.io',
                'git_url': 'https://github.com/INF800/random-headers',
                'lib_path': 'random_headers'},
  'syms': { 'random_headers.core': {'random_headers.core.foo': ('core.html#foo', 'random_headers/core.py')},
            'random_headers.static_headers': { 'random_headers.static_headers.get_header': ( 'static_headers.html#get_header',
                                                                                             'random_headers/static_headers.py')}}}
